/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
description = "Implementation of 10 methods for the class Range"
version = "1.0"

plugins {
  id("org.jetbrains.kotlin.jvm") version "1.3.72"
  id("org.jetbrains.dokka") version "0.10.0"
  application
}

repositories {
  // Use jcenter for resolving dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

dependencies {
  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

  // Use the Kotlin test library.
  testImplementation("org.jetbrains.kotlin:kotlin-test")

  // Use the Kotlin JUnit integration.
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

tasks.dokka {    
  outputFormat = "html"
  outputDirectory = "$buildDir/javadoc"
}

application {
  mainClassName = "range.testing.RangeKt"
}
